### ISSUE TITLE
A way to specify visibility filter for `Load image with metadata`?

### ISSUE THREAD

**Issue by Lex-DRL** [crystian/ComfyUI-Crystools#135]
**Is your feature request related to a problem? Please describe.**
It's possible to have extra files in the `input` folder (at least, hidden "dot" files), which clutter the file list when selecting an image. Especially if you put the entire `input` folder in version control or, even worse, have multiple of those in subfolders (imagine the entire contents of `.git` folder being listed there).

**Describe the solution you'd like**
Some option in Crystools settings with a file-matching pattern would solve the issue. And probably, by default it should be filled with something like `.*;Thumbs.db;*.DS_Store;*.lock`.

**Describe alternatives you've considered**
Another custom node ([rgthree](https://github.com/rgthree/rgthree-comfy)) allows us to nest subdirectories in menus, but it's only a workaround. Ideally, those useless files/subfolders should be filtered out off the list.

**Additional context**
Probably, a second "hidden" internal filter should be applied on top of it - showing only those file types which the node supports.

**Comment by julien-moment** [comment]
+1 for this feature!

I was about to post a similar request regarding the issue with hidden dot files that duplicate each file in the input folder. This duplication makes it a bit tedious to ensure you’re linking the correct file, especially since the dot (.) indicating a hidden file is small and easy to miss. Enhancing this feature would greatly improve usability.

**Comment by crystian** [comment]
done, check on new release

**Comment by Lex-DRL** [comment]
@crystian I can't reopen the issue myself.

![Image](https://github.com/user-attachments/assets/eacf7741-b560-4442-a634-6126a2f3f2fd)

I'm on `1.25.2` now, and still don't see any such filter in settings. Screenshot is above.
